public class ListOfNames{
	private ListOfNames(){}
	public static String [] names = {"Agent S","Agnes","Al","Alfonso","Alice","Alli",
		"Amelia","Anabelle","Anchovy","Angus","Anicotti","Ankha","Annalisa",
		"Annalise","Antonio","Apollo","Apple","Astrid","Aurora","Ava",
		"Avery","Axel","Baabara","Bam","Bangle","Barold","Beardo",
		"Beau","Becky","Bella","Benedict","Benjamin","Bertha","Bettina",
		"Bianca","Biff","Big Top","Bill","Biskit","Blaire","Blanche",
		"Bluebear","Bob","Bonbon","Bones","Boomer","Boone","Bree",
		"Broccolo","Broffina","Bruce","Bubbles","Buck","Bud","Bunnie",
		"Butch","Cally","Camofrog","Canberra","Carmen","Caroline","Celia",
		"Cesar","Chadder","Charlise","Cheri","Cherry","Chester","Chevre",
		"Chief","Chops","Chow","Chrissy","Claudia","Clay","Clyde",
		"Coach","Cobb","Coco","Cole","Colton","Cookie","Cousteau",
		"Cranston","Croque","Cube","Curlos","Curly","Curt","Cyrano",
		"Daisy","Deena","Deirdre","Del","Deli","Derwin","Diana",
		"Diva","Dizzy","Doc","Dora","Dotty","Drago","Drake",
		"Drift","Ed","Egbert","Elise","Elmer","Eloise","Elvis",
		"Erik","Eugene","Eunice","Fang","Fauna","Felicity","Filbert",
		"Flip","Flo","Flora","Flurry","Francine","Frank","Freckles",
		"Freya","Friga","Frita","Frobert","Fuchsia","Gabi","Gala",
		"Gaston","Gayle","Genji","Gigi","Gladys","Gloria","Goldie",
		"Goose","Graham","Greta","Grizzly","Groucho","Gruff","Gwen",
		"Hamlet","Hamphrey","Hans","Harry","Hazel","Henry","Hippeux",
		"Hopper","Hugh","Iggly","Jacques","Jambette","Jay","Jeremiah",
		"Jitters","Joey","Julian","Kabuki","Katt","Keaton","Ken",
		"Ketchup","Kevin","Kid Cat","Kidd","Kiki","Kitt","Kitty",
		"Klaus","Knox","Kody","Kyle","Leonardo","Lily","Limberg",
		"Lionel","Lobo","Lolly","Lopez","Lucha","Lucky","Lucy",
		"Lyman","Mac","Maelle","Mallary","Maple","Marcel","Marcie",
		"Margie","Marina","Marshal","Mathilda","Melba","Merengue","Merry",
		"Midge","Mint","Mira","Miranda","Mitzi","Moe","Molly",
		"Monique","Monty","Moose","Mott","Muffy","Nan","Nana",
		"Naomi","Nate","Nibbles","O'Hare","Octavian","Olaf","Olivia",
		"Opal","Ozzie","Pancetti","Pango","Papi","Pashmina","Pate",
		"Patty","Paula","Peaches","Peanut","Pecan","Peck","Peewee",
		"Peggy","Pekoe","Penelope","Phil","Phoebe","Pierce","Pietro",
		"Pinky","Pippy","Pompom","Poncho","Poppy","Portia","Prince",
		"Puck","Puddles","Pudge","Punchy","Purrl","Queenie","Quillson",
		"Rasher","Ren\u00e9e","Rhonda","Ribbot","Ricky","Rizzo","Roald",
		"Robin","Rocco","Rocket","Rod","Rodeo","Rodney","Rolf",
		"Rooney","Rory","Roscoe","Rosie","Rowan","Ruby","Rudy",
		"Sally","Samson","Savannah","Scoot","Shari","Sheldon","Shep",
		"Simon","Skye","Sly","Snake","Soleil","Sparro","Spork",
		"Sprinkle","Static","Sterling","Stinky","Stitches","Sydney","Sylvia",
		"T-Bone","Tabby","Tammi","Tammy","Tangy","Tank","Teddy",
		"Tex","Tia","Tiffany","Timbra","Tipper","Tom","Truffles",
		"Tucker","Tutu","Twiggy","Velma","Vesta","Vic","Victoria",
		"Violet","Vladimir","Walker","Walt","Wart Jr.","Wendy","Whitney",
		"Willow","Winnie","Wolfgang","Yuka","Zell","Zucker"	};
}
